"""Sovereign dashboard — performance tracking as a self-contained HTML page.

Pulls live account + portfolio history from Alpaca, closed-trade stats from
sovereign_state/trade_log.jsonl, the latest composite signals, macro regime,
and the congressional member leaderboard. Writes:

    sovereign_results/dashboard.html   (open in any browser; light/dark aware)

and prints a CLI summary. Regenerated by cron at market close.

Usage:  python3 sovereign_dashboard.py
"""

import html
import json
import logging
from datetime import datetime

from sovereign_config import (DATA_DIR, RESULTS_DIR, STATE_DIR, alpaca_keys,
                              load_json)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
log = logging.getLogger("dashboard")

OUT_FILE = RESULTS_DIR / "dashboard.html"


# --------------------------------------------------------------------------
# Data gathering
# --------------------------------------------------------------------------

def gather() -> dict:
    from alpaca.trading.client import TradingClient
    from alpaca.trading.requests import GetPortfolioHistoryRequest

    key, secret, paper = alpaca_keys()
    client = TradingClient(key, secret, paper=paper)
    account = client.get_account()
    positions = client.get_all_positions()

    equity_curve = []
    try:
        hist = client.get_portfolio_history(GetPortfolioHistoryRequest(
            period="3M", timeframe="1D"))
        for ts, eq in zip(hist.timestamp, hist.equity):
            if eq is not None:
                equity_curve.append({"date": datetime.fromtimestamp(ts).strftime("%m/%d"),
                                     "equity": float(eq)})
    except Exception as e:
        log.warning("Portfolio history failed: %s", e)

    trades = []
    trade_log = STATE_DIR / "trade_log.jsonl"
    if trade_log.exists():
        for line in trade_log.read_text().splitlines():
            try:
                trades.append(json.loads(line))
            except json.JSONDecodeError:
                continue

    sells = [t for t in trades if t.get("action") == "sell"]
    stops = sum(1 for t in sells if "STOP" in t.get("why", ""))
    targets = sum(1 for t in sells if "TARGET" in t.get("why", ""))

    snaps = sorted(RESULTS_DIR.glob("signals_*.json"), reverse=True)
    signals = load_json(snaps[0], {}) if snaps else {}
    regime = load_json(RESULTS_DIR / "macro_regime.json", {})
    members = load_json(DATA_DIR / "member_scores.json", {}).get("members", {})
    state = load_json(STATE_DIR / "positions_state.json", {})
    halt = load_json(STATE_DIR / "halt.json", {})

    return {
        "paper": paper,
        "equity": float(account.equity),
        "last_equity": float(account.last_equity or account.equity),
        "cash": float(account.cash),
        "positions": [{
            "symbol": p.symbol, "qty": float(p.qty),
            "entry": float(p.avg_entry_price), "price": float(p.current_price),
            "value": float(p.market_value), "pl": float(p.unrealized_pl),
            "pl_pct": float(p.unrealized_plpc) * 100,
            "stop": state.get(p.symbol, {}).get("stop"),
            "target": state.get(p.symbol, {}).get("target"),
        } for p in positions],
        "equity_curve": equity_curve,
        "trades": trades[-20:],
        "n_buys": sum(1 for t in trades if t.get("action") == "buy"),
        "n_sells": len(sells), "n_stops": stops, "n_targets": targets,
        "signals": signals, "regime": regime, "members": members,
        "halted": halt.get("date") == datetime.now().strftime("%Y-%m-%d"),
        "generated": datetime.now().strftime("%Y-%m-%d %H:%M"),
    }


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------

CSS = """
:root{--surface:#fcfcfb;--page:#f9f9f7;--ink:#0b0b0b;--ink2:#52514e;--muted:#898781;
--grid:#e1e0d9;--axis:#c3c2b7;--series:#2a78d6;--good:#006300;--bad:#d03b3b;
--border:rgba(11,11,11,.10)}
@media(prefers-color-scheme:dark){:root{--surface:#1a1a19;--page:#0d0d0d;--ink:#fff;
--ink2:#c3c2b7;--grid:#2c2c2a;--axis:#383835;--series:#3987e5;--good:#0ca30c;
--border:rgba(255,255,255,.10)}}
*{box-sizing:border-box;margin:0}
body{font:14px/1.45 system-ui,-apple-system,"Segoe UI",sans-serif;background:var(--page);
color:var(--ink);padding:24px;max-width:1080px;margin:0 auto}
h1{font-size:20px;margin-bottom:2px} h2{font-size:14px;color:var(--ink2);margin:28px 0 10px}
.sub{color:var(--muted);font-size:12px;margin-bottom:20px}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}
.tile{background:var(--surface);border:1px solid var(--border);border-radius:10px;padding:14px 16px}
.tile .label{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.04em}
.tile .value{font-size:26px;font-weight:650;margin-top:2px}
.tile .delta{font-size:12px;margin-top:2px;color:var(--ink2)}
.up{color:var(--good)} .down{color:var(--bad)}
.card{background:var(--surface);border:1px solid var(--border);border-radius:10px;padding:16px;overflow-x:auto}
table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums}
th{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.04em;
text-align:right;padding:6px 10px;border-bottom:1px solid var(--grid)}
th:first-child,td:first-child{text-align:left}
td{padding:6px 10px;text-align:right;border-bottom:1px solid var(--grid);font-size:13px}
tr:last-child td{border-bottom:none}
.badge{display:inline-block;padding:2px 8px;border-radius:999px;font-size:11px;
font-weight:600;border:1px solid var(--border);color:var(--ink2)}
.chart-wrap{position:relative}
#tip{position:absolute;pointer-events:none;background:var(--surface);color:var(--ink);
border:1px solid var(--border);border-radius:6px;padding:4px 8px;font-size:12px;
display:none;white-space:nowrap;box-shadow:0 2px 8px rgba(0,0,0,.12)}
details{margin-top:8px;color:var(--ink2);font-size:12px}
svg text{fill:var(--muted);font:11px system-ui,sans-serif}
"""


def _fmt_money(x): return f"${x:,.2f}"


def _cls(x): return "up" if x > 0 else "down" if x < 0 else ""


def _equity_svg(curve: list, width=1000, height=220) -> str:
    if len(curve) < 2:
        return "<p class='sub'>Not enough history for an equity curve yet.</p>"
    pad_l, pad_r, pad_t, pad_b = 56, 12, 12, 26
    vals = [p["equity"] for p in curve]
    lo, hi = min(vals), max(vals)
    if hi - lo < 1e-9:
        lo, hi = lo - 1, hi + 1
    span = hi - lo
    lo -= span * 0.06
    hi += span * 0.06
    iw, ih = width - pad_l - pad_r, height - pad_t - pad_b

    def x(i): return pad_l + iw * i / (len(curve) - 1)
    def y(v): return pad_t + ih * (1 - (v - lo) / (hi - lo))

    pts = " ".join(f"{x(i):.1f},{y(p['equity']):.1f}" for i, p in enumerate(curve))

    grid, labels = [], []
    for frac in (0, .5, 1):
        v = lo + (hi - lo) * frac
        yy = y(v)
        grid.append(f'<line x1="{pad_l}" y1="{yy:.1f}" x2="{width - pad_r}" y2="{yy:.1f}" '
                    f'stroke="var(--grid)" stroke-width="1"/>')
        labels.append(f'<text x="{pad_l - 8}" y="{yy + 4:.1f}" text-anchor="end">{v:,.0f}</text>')
    for i in (0, len(curve) // 2, len(curve) - 1):
        labels.append(f'<text x="{x(i):.1f}" y="{height - 8}" text-anchor="middle">'
                      f'{curve[i]["date"]}</text>')

    data_json = html.escape(json.dumps(curve), quote=True)
    return f"""
<div class="chart-wrap">
<svg id="eq" viewBox="0 0 {width} {height}" width="100%" data-curve="{data_json}"
     data-padl="{pad_l}" data-padr="{pad_r}" role="img" aria-label="Equity curve">
  {''.join(grid)}
  <line x1="{pad_l}" y1="{height - pad_b}" x2="{width - pad_r}" y2="{height - pad_b}"
        stroke="var(--axis)" stroke-width="1"/>
  <polyline points="{pts}" fill="none" stroke="var(--series)" stroke-width="2"
            stroke-linejoin="round" stroke-linecap="round"/>
  <line id="xh" x1="0" y1="{pad_t}" x2="0" y2="{height - pad_b}" stroke="var(--axis)"
        stroke-width="1" stroke-dasharray="3 3" visibility="hidden"/>
  <circle id="dot" r="4" fill="var(--series)" stroke="var(--surface)" stroke-width="2"
          visibility="hidden"/>
  {''.join(labels)}
</svg>
<div id="tip"></div>
</div>
<details><summary>Equity data</summary><table><tr><th>Date</th><th>Equity</th></tr>
{''.join(f"<tr><td>{p['date']}</td><td>{_fmt_money(p['equity'])}</td></tr>" for p in curve[-15:])}
</table></details>
<script>
(function(){{
  const svg=document.getElementById('eq'),tip=document.getElementById('tip'),
        xh=document.getElementById('xh'),dot=document.getElementById('dot'),
        curve=JSON.parse(svg.dataset.curve),padl=+svg.dataset.padl,padr=+svg.dataset.padr;
  const vb=svg.viewBox.baseVal,iw=vb.width-padl-padr;
  const vals=curve.map(p=>p.equity);let lo=Math.min(...vals),hi=Math.max(...vals);
  const sp=(hi-lo)||2;lo-=sp*0.06;hi+=sp*0.06;
  svg.addEventListener('mousemove',e=>{{
    const r=svg.getBoundingClientRect(),sx=vb.width/r.width;
    const mx=(e.clientX-r.left)*sx;
    let i=Math.round((mx-padl)/iw*(curve.length-1));
    i=Math.max(0,Math.min(curve.length-1,i));
    const cx=padl+iw*i/(curve.length-1);
    const cy=12+(vb.height-38)*(1-(curve[i].equity-lo)/(hi-lo));
    xh.setAttribute('x1',cx);xh.setAttribute('x2',cx);xh.setAttribute('visibility','visible');
    dot.setAttribute('cx',cx);dot.setAttribute('cy',cy);dot.setAttribute('visibility','visible');
    tip.style.display='block';
    tip.style.left=Math.min(cx/sx+12,r.width-120)+'px';
    tip.style.top=(cy/sx-34)+'px';
    tip.textContent=curve[i].date+' — $'+curve[i].equity.toLocaleString(undefined,
      {{minimumFractionDigits:2,maximumFractionDigits:2}});
  }});
  svg.addEventListener('mouseleave',()=>{{tip.style.display='none';
    xh.setAttribute('visibility','hidden');dot.setAttribute('visibility','hidden');}});
}})();
</script>"""


def render(d: dict) -> str:
    day_pl = d["equity"] - d["last_equity"]
    day_pct = day_pl / d["last_equity"] * 100 if d["last_equity"] else 0
    total_pl = sum(p["pl"] for p in d["positions"])
    closed = d["n_sells"]
    win_rate = d["n_targets"] / closed * 100 if closed else None
    regime = d["regime"] or {}

    tiles = f"""
<div class="tiles">
  <div class="tile"><div class="label">Equity {'(paper)' if d['paper'] else '(LIVE)'}</div>
    <div class="value">{_fmt_money(d['equity'])}</div>
    <div class="delta {_cls(day_pl)}">{day_pl:+,.2f} ({day_pct:+.2f}%) today</div></div>
  <div class="tile"><div class="label">Cash</div>
    <div class="value">{_fmt_money(d['cash'])}</div></div>
  <div class="tile"><div class="label">Open P/L</div>
    <div class="value {_cls(total_pl)}">{total_pl:+,.2f}</div>
    <div class="delta">{len(d['positions'])} position{'s' if len(d['positions']) != 1 else ''}</div></div>
  <div class="tile"><div class="label">Closed trades</div>
    <div class="value">{closed}</div>
    <div class="delta">{d['n_targets']} targets · {d['n_stops']} stops"""
    tiles += (f" · {win_rate:.0f}% wins" if win_rate is not None else "") + "</div></div>"
    tiles += f"""
  <div class="tile"><div class="label">Macro regime</div>
    <div class="value" style="font-size:20px">{regime.get('regime', '—')}</div>
    <div class="delta">score {regime.get('score', 0):+.2f} · exposure x{regime.get('exposure_multiplier', '—')}</div></div>
</div>"""

    halt_banner = ("<p class='badge' style='color:var(--bad);border-color:var(--bad)'>"
                   "⛔ CIRCUIT BREAKER ACTIVE — no new entries today</p>" if d["halted"] else "")

    pos_rows = "".join(
        f"<tr><td>{p['symbol']}</td><td>{p['qty']:.4f}</td><td>{_fmt_money(p['entry'])}</td>"
        f"<td>{_fmt_money(p['price'])}</td><td>{_fmt_money(p['value'])}</td>"
        f"<td class='{_cls(p['pl'])}'>{p['pl']:+,.2f} ({p['pl_pct']:+.1f}%)</td>"
        f"<td>{p['stop'] if p['stop'] else '—'}</td><td>{p['target'] if p['target'] else '—'}</td></tr>"
        for p in d["positions"]) or "<tr><td colspan=8>No open positions</td></tr>"

    sig_rows = ""
    for t, s in sorted((d["signals"].get("signals") or {}).items(),
                       key=lambda kv: kv[1]["score"], reverse=True)[:12]:
        top = sorted(s["components"], key=lambda c: abs(c["score"] * c["weight"]), reverse=True)
        drivers = "; ".join(f"{c['name']} {c['detail']}" for c in top[:2] if c["detail"])
        flags = " ".join(f"⚠️{html.escape(f)}" for f in s.get("risk_flags", []))
        sig_rows += (f"<tr><td>{t}</td><td class='{_cls(s['score'])}'>{s['score']:+.3f}</td>"
                     f"<td>{s['conviction']}</td>"
                     f"<td style='text-align:left'>{html.escape(drivers)} {flags}</td></tr>")
    sig_rows = sig_rows or "<tr><td colspan=4>No signal snapshot yet — run a scan</td></tr>"

    mem_rows = "".join(
        f"<tr><td>{html.escape(m)}</td><td>{v['n_trades']}</td>"
        f"<td class='{_cls(v['mean_excess_30td'])}'>{v['mean_excess_30td']:+.1%}</td>"
        f"<td>{v['hit_rate']:.0%}</td><td>{v['weight']:.2f}</td></tr>"
        for m, v in sorted(d["members"].items(), key=lambda kv: kv[1]["weight"],
                           reverse=True)[:10]
    ) or "<tr><td colspan=5>Run: python3 member_scoring.py build</td></tr>"

    trade_rows = "".join(
        f"<tr><td>{t.get('timestamp', '')[:16]}</td><td>{t.get('action', '').upper()}</td>"
        f"<td>{t.get('ticker', '')}</td>"
        f"<td>{_fmt_money(t['notional']) if t.get('notional') else '—'}</td>"
        f"<td style='text-align:left'>{html.escape((t.get('why') or t.get('thesis') or '')[:90])}</td></tr>"
        for t in reversed(d["trades"])) or "<tr><td colspan=5>No trades logged yet</td></tr>"

    return f"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sovereign Dashboard</title><style>{CSS}</style></head><body>
<h1>🏦 Sovereign — {'Paper' if d['paper'] else 'LIVE'} Trading Dashboard</h1>
<p class="sub">Generated {d['generated']} · goal: fund the Hand ($400) · discipline over ambition</p>
{halt_banner}
{tiles}
<h2>Equity — last 3 months</h2>
<div class="card">{_equity_svg(d['equity_curve'])}</div>
<h2>Open positions</h2>
<div class="card"><table>
<tr><th>Symbol</th><th>Qty</th><th>Entry</th><th>Price</th><th>Value</th><th>P/L</th><th>Stop</th><th>Target</th></tr>
{pos_rows}</table></div>
<h2>Latest composite signals</h2>
<div class="card"><table>
<tr><th>Ticker</th><th>Score</th><th>Conviction</th><th style="text-align:left">Top drivers</th></tr>
{sig_rows}</table></div>
<h2>Congressional leaderboard (30-trading-day excess vs SPY)</h2>
<div class="card"><table>
<tr><th>Member</th><th>N</th><th>Excess</th><th>Hit%</th><th>Weight</th></tr>
{mem_rows}</table></div>
<h2>Recent trades</h2>
<div class="card"><table>
<tr><th>When</th><th>Action</th><th>Ticker</th><th>Notional</th><th style="text-align:left">Why</th></tr>
{trade_rows}</table></div>
</body></html>"""


def main():
    d = gather()
    OUT_FILE.write_text(render(d))
    log.info("Dashboard written to %s", OUT_FILE)

    day_pl = d["equity"] - d["last_equity"]
    print(f"\nSOVEREIGN — equity {_fmt_money(d['equity'])} ({day_pl:+,.2f} today) | "
          f"cash {_fmt_money(d['cash'])} | {len(d['positions'])} positions | "
          f"regime {(d['regime'] or {}).get('regime', '?')}"
          f"{' | ⛔ HALTED' if d['halted'] else ''}")
    for p in d["positions"]:
        print(f"  {p['symbol']:6s} {_fmt_money(p['value']):>10s}  "
              f"{p['pl']:+7.2f} ({p['pl_pct']:+.1f}%)  stop={p['stop']} target={p['target']}")
    print(f"Dashboard: {OUT_FILE}")


if __name__ == "__main__":
    main()
